# Generated by Django 4.2 on 2024-08-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userdata_is_verified_alter_userdata_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
