# Generated by Django 4.2 on 2024-08-08 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_todo_user_alter_userdata_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assigned_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
