# Generated by Django 4.2 on 2024-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_todo_assigned_by_todo_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
